#!/usr/bin/env perl

# jira-commention
# Replace "@"-prefixed email addresses in the input with Atlassian Wiki
# formatted account IDs.

# Copyright (c) 2024  Teddy Wing
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.


use strict;
use warnings;
use v5.10;

use constant {
	EX_NOUSER => 67,
};

while (<<>>) {
	my $line = $_;

	$line =~ s/(?<prefix>\s)@(?<email>[^\s]+)/$+{prefix} . jira_user_id_from_email($+{email})/eg;

	print $line;
}

sub jira_user_id_from_email {
	my ($email) = @_;

	my $jira_user_id = qx{
		curl \\
			--silent \\
			--user 'user\@example.com:MiY8LFUPxPvxyJJMihTTr8Q4' \\
			--header 'Accept: application/json' \\
			--location 'https://your-domain.atlassian.net/rest/api/2/user/search?query=${email}' \\
		| jq --raw-output '.[0].accountId'
	};
	chomp $jira_user_id;

	if ($jira_user_id eq 'null') {
		say STDERR "error: no Jira user ID for email '$email'";
		exit EX_NOUSER;
	}

	my $at_mention_text = '[~accountid:' . $jira_user_id . ']';

	return $at_mention_text;
}
